//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTogether.Commons.EmailSender.Templates {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplates() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatTogether.Commons.EmailSender.Templates.HtmlTemplates", typeof(HtmlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;b&gt;Witaj {{email}}&lt;/b&gt;
        ///&lt;br&gt;Aby potwierdzić zmianę adresu email na &lt;b&gt;{{newEmail}}&lt;/b&gt; klikij w poniższy link.
        ///&lt;br&gt;
        ///{{confirmationLink}}
        ///&lt;br&gt;
        ///Aby zakończyć proces zmiany adresu email, zostanie wysłana kolejna wiadomość na nowy adres email w celu potwierdzenia operacji..
        /// </summary>
        internal static string ChangeEmailRequestTemplate {
            get {
                return ResourceManager.GetString("ChangeEmailRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;b&gt;Witaj {{email}}&lt;/b&gt;
        ///&lt;br&gt;Kliknij w poniższy link, aby zmienić hasło.
        ///&lt;br&gt;
        ///{{confirmationLink}}.
        /// </summary>
        internal static string ChangePasswordRequestTemplate {
            get {
                return ResourceManager.GetString("ChangePasswordRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;b&gt;Witaj {{email}}&lt;/b&gt;
        ///&lt;br&gt;Aby zakończyć proces zmiany adresu email kliknij w poniższy link.
        ///&lt;br&gt;
        ///{{confirmationLink}}
        ///&lt;br&gt;.
        /// </summary>
        internal static string ConfirmChangeEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmChangeEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;b&gt;Witaj {{email}}&lt;/b&gt;
        ///&lt;br&gt;Kliknij w poniższy link, aby potwierdzić utworzenie konta.
        ///&lt;br&gt;
        ///{{confirmationLink}}.
        /// </summary>
        internal static string ConfirmRegistrationTemplate {
            get {
                return ResourceManager.GetString("ConfirmRegistrationTemplate", resourceCulture);
            }
        }
    }
}
