//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTogether.Commons.EmailSender.Templates {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplates() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatTogether.Commons.EmailSender.Templates.HtmlTemplates", typeof(HtmlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;table width=&quot;100%&quot; ; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; font-size: 1.1em; background-color: #d9ddf2;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///                &lt;table width=&quot;550px&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; style=&quot;margin: 10px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                      [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ChangeEmailRequestTemplate {
            get {
                return ResourceManager.GetString("ChangeEmailRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;table width=&quot;100%&quot; ; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; font-size: 1.1em; background-color: #d9ddf2;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///                &lt;table width=&quot;550px&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; style=&quot;margin: 10px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                      [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ChangePasswordRequestTemplate {
            get {
                return ResourceManager.GetString("ChangePasswordRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;table width=&quot;100%&quot; ; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; font-size: 1.1em; background-color: #d9ddf2;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///                &lt;table width=&quot;550px&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; style=&quot;margin: 10px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                      [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ConfirmChangeEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmChangeEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;table width=&quot;100%&quot; ; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; font-size: 1.1em; background-color: #d9ddf2;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///                &lt;table width=&quot;550px&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; style=&quot;margin: 10px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                      [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ConfirmRegistrationTemplate {
            get {
                return ResourceManager.GetString("ConfirmRegistrationTemplate", resourceCulture);
            }
        }
    }
}
